Python 3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.
>>> import re
... 
... def validate_password(pwd):
...     if len(pwd) < 8:
...         return False
... 
...     if not re.search(r"\d", pwd):  # number check
...         return False
... 
...     if not re.search(r"[!@#$%^&*(),.?\":{}|<>]", pwd):  # special char check
...         return False
... 
...     return True
... 
... 
... passwords = ["abc", "123456", "Pass@123", "Admin"]
... 
... print("🔐 Password Strength Report\n")
... 
... for pwd in passwords:
...     result = "PASS ✅" if validate_password(pwd) else "FAIL ❌"
...     print(f"{pwd}: {result}")
